icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "custom"
command = "echo '\uf007' $(whoami)"
interval= "once"

[[block]]
block = "custom"
json = true
command = "~/.config/i3status-rust/handle_net_format.sh"
[[block.click]]
button = "right"
cmd = "~/.config/i3status-rust/handle_net_format.sh airplane"
sync = true
update = true

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%H:%M:%S %d/%m') "
